### ISSUE TITLE
Basket returning a 404 error

### ISSUE THREAD

**Issue by mtdenton** [MozillaFoundation/foundation.mozilla.org#10657]
### Describe the bug
We're getting a 404 back from Basket when we send submissions from foundation.mozilla.org. The error comes back as a 500 on the client side, but sending from local gives this traceback:

```
Internal Server Error: /api/campaign/signups/0/
foundationmozillaorg-backend-1             | Traceback (most recent call last):
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
foundationmozillaorg-backend-1             |     response = get_response(request)
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
foundationmozillaorg-backend-1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
foundationmozillaorg-backend-1             |   File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
foundationmozillaorg-backend-1             |     return func(*args, **kwds)
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
foundationmozillaorg-backend-1             |     return view_func(*args, **kwargs)
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
foundationmozillaorg-backend-1             |     return func(request, *args, **kwargs)
foundationmozillaorg-backend-1             |   File "/app/network-api/networkapi/campaign/views.py", line 86, in signup_submission_view
foundationmozillaorg-backend-1             |     return signup_submission(request, signup)
foundationmozillaorg-backend-1             |   File "/app/network-api/networkapi/campaign/views.py", line 164, in signup_submission
foundationmozillaorg-backend-1             |     response = basket.subscribe(data["email"], data["newsletters"], **basket_additional)
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/basket/base.py", line 161, in subscribe
foundationmozillaorg-backend-1             |     return request('post', 'subscribe', data=kwargs, headers=headers)
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/basket/base.py", line 131, in request
foundationmozillaorg-backend-1             |     return parse_response(res)
foundationmozillaorg-backend-1             |   File "/app/dockerpythonvenv/lib/python3.9/site-packages/basket/base.py", line 96, in parse_response
foundationmozillaorg-backend-1             |     raise BasketException(desc,
foundationmozillaorg-backend-1             | basket.base.BasketException: 404 request returned from basket: b'<html>\n<head>\n  <title>404 - Page not found - Basket</title>\n</head>\n<body>\n  <h1>404 - Page not found - Basket</h1>\n</body>\n</html>\n'
```

**Comment by mtdenton** [comment]
Our `BASKET_URL` environment variable, which hasn't changed in years likely, is suddenly not acceptable with a trailing slash at the end. So the the variable from `https://basket-dev.allizom.org/` to `https://basket-dev.allizom.org` on staging has fixed the issue there.

Updating the same environment variable on prod from `https://basket.mozilla.org/` to `https://basket.mozilla.org` has fixed the issue.

**Comment by mmmavis** [comment]
I wonder if Playwright can help us catch errors like this. Will create a ticket to investigate.
