### ISSUE TITLE
Localised PNI pages are crashing

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11042]
### Describe the bug

Localized PNI About pages are crashing
- The English pages are loading fine.
- Loading the pages while not being logged in also works - I suspect the previously working pages are still cached, but that might not last long…
- All translated pages do not load and throw a 500 Server Error

### To Reproduce
1. Go to 'https://foundation.mozilla.org/fr/privacynotincluded/about/' or 'https://foundation.mozilla.org/de/privacynotincluded/about/methodology/'
2. See the 500 error

### Expected behavior
The localised pages load

### Additional context
Error stack trace:

```console
 Aug 29 09:21:19 foundation-mozilla-org app/web.6 Traceback (most recent call last):
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Aug 29 09:21:19 foundation-mozilla-org app/web.6     response = get_response(request)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Aug 29 09:21:19 foundation-mozilla-org app/web.6     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return callback(request, *args, **kwargs)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return func(*args, **kwds)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/views.py", line 28, in serve
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return page.serve(request, *args, **kwargs)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/contrib/routable_page/models.py", line 171, in serve
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return view(request, *args, **kwargs)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/homepage.py", line 226, in about_methodology_page
Aug 29 09:21:19 foundation-mozilla-org app/web.6     context = self.get_context(request)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/homepage.py", line 374, in get_context
Aug 29 09:21:19 foundation-mozilla-org app/web.6     products = get_product_subset(
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/homepage.py", line 541, in get_product_subset
Aug 29 09:21:19 foundation-mozilla-org app/web.6     products = sort_average(products)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/utils.py", line 45, in sort_average
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return sorted(products, key=lambda p: p.creepiness)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/utils.py", line 45, in <lambda>
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return sorted(products, key=lambda p: p.creepiness)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py", line 657, in creepiness
Aug 29 09:21:19 foundation-mozilla-org app/web.6     product = self.original_product
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py", line 629, in original_product
Aug 29 09:21:19 foundation-mozilla-org app/web.6     original = get_original_by_slug(ProductPage, slug)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/network-api/networkapi/wagtailpages/utils.py", line 483, in get_original_by_slug
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return Model.objects.get(slug=slug, locale=DEFAULT_LOCALE_ID)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
Aug 29 09:21:19 foundation-mozilla-org app/web.6     return getattr(self.get_queryset(), name)(*args, **kwargs)
Aug 29 09:21:19 foundation-mozilla-org app/web.6   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
Aug 29 09:21:19 foundation-mozilla-org app/web.6     raise self.model.DoesNotExist(
Aug 29 09:21:19 foundation-mozilla-org app/web.6 networkapi.wagtailpages.pagemodels.buyersguide.products.ProductPage.DoesNotExist: ProductPage matching query does not exist.
Aug 29 13:48:43 foundation-mozilla-org app/web.6 Internal Server Error: /de/privacynotincluded/about/
```

**Comment by jhonatan-lopes** [comment]
Tested on staging and it is working well.

1. Changed the slug on the [original English Honda page](https://foundation.mofostaging.net/en/privacynotincluded/honda-not-matching-translated-slugs/) from `honda` to `honda-not-matching-translated-slugs`
2. Translated the English Honda page to Portuguese (Brazil) and changed the slug to `honda`
3. Accessed the [Portuguese page](https://foundation.mofostaging.net/pt-BR/privacynotincluded/honda/) and see that it doesn't return an error
4. Accessed the [Portuguese about page](https://foundation.mofostaging.net/pt-BR/privacynotincluded/about/) and see that it doesn't return a server error.
