### ISSUE TITLE
Review apps can't set up DNS records

### ISSUE THREAD

**Issue by jhonatan-lopes** [MozillaFoundation/foundation.mozilla.org#11536]
When preparing a review app, during the "Run scripts & scale dynos" phase, the fake data generation script fails during the "Setting up DNS records and Sites for review app":

```
wait parent timeout: Operation not permitted

Seeding random numbers with: 1236266

Generating Images

Generating Fake News

Generating Highlights

Generating Locale

Generating blank Homepage

Generating a Homepage

Updated the default Site

Assigning images to areas of focus

Generating "who we are" Page (PrimaryPage)

Generating child pages for "who we are" page

Generating "what we do" Page (PrimaryPage)

Generating an empty Participate Page

Generating a profile that can be used for percy testing.

Generating other profiles

Generating a blog namespace

Generating blog posts under namespace

Generating PNI Homepage

Generating visual regression test products

Generating 52 ProductPages

Crosslinking related products

Generating Buyer's Guide product updates

Generating predictable PNI images

Generating buyers guide editorial content

Generating PNI Annual Consumer Creep-O-Meter Page for Year 2023

Generating a campaign index page

Generating Bannered Campaign Pages under namespace

campaign index page exists

Generating Campaign Pages under namespace

Generating Donation Modals for Campaign Pages

Generating single-page CampaignPage

Generating multi-page CampaignPage

campaign index page exists

Generating Dear Internet under campaigns namespace

Generating Homepage Focus Areas and Spotlights

Generating Partner Logos

Generating Homepage Take Actions

Generating Homepage Blogs and Highlights

Generating an empty Initiatives Page

initiatives page exists

Generating Opportunity Pages as child pages of an Initiative Page

Generating single-page OpportunityPage

Generating multi-page OpportunityPage

Generating Participate Highlights

Generating a Styleguide Page

campaign index page exists

Generating YouTube Regrets Page under campaigns namespace

Generating Regrets Reporter Page under campaigns namespace

Generating a youtube bannered campaign page and extension landing page

Generating research hub

Generating rcc playbook

Generating Homepage Cause Statement Link

Generating Mozfest Homepage

Generating a Homepage

Creating MozFest Site record in Wagtail

Generating Mozfest sub-pages

Generating Mozfest landing-pages

Generating Donate Site Landing page

Generating a Landing page

Generating a Help page

[32;1mDone![0m

Setting up DNS records and Sites for review app

Traceback (most recent call last):

  File "/app/network-api/manage.py", line 35, in <module>

    execute_from_command_line(sys.argv)

  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

    utility.execute()

  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute

    output = self.handle(*args, **options)

  File "/app/network-api/networkapi/management/commands/review_app_setup.py", line 135, in handle

    self.update_site_hostnames()

  File "/app/network-api/networkapi/management/commands/review_app_setup.py", line 118, in update_site_hostnames

    site = Site.objects.get(site_name=site_name)

  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get

    raise self.model.DoesNotExist(

wagtail.models.sites.Site.DoesNotExist: Site matching query does not exist
```

**Comment by mtdenton** [comment]
I don't think the `Donate` `Site` is being created. Did something change here? We query for `site_name` here:

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/9034d93977680816ac25dd06e595aeada62d6aaa/network-api/networkapi/management/commands/review_app_setup.py#L118

We get the site mapping here:
https://github.com/MozillaFoundation/foundation.mozilla.org/blob/9034d93977680816ac25dd06e595aeada62d6aaa/network-api/networkapi/management/commands/review_app_setup.py#L60-L64

`WagtailSite`s are being created for `Mozilla Festival` and `Foundation Home Page`, but not for `Donate` anywhere I can see:

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/9034d93977680816ac25dd06e595aeada62d6aaa/network-api/networkapi/mozfest/factory.py#L83-L89

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/9034d93977680816ac25dd06e595aeada62d6aaa/network-api/networkapi/wagtailpages/factory/homepage.py#L81-L88

(`Site` is being imported as `WagtailSite`)

Do we need to remove Donate from this list? Even more curious, why are we just now running into problems with this?
