### ISSUE TITLE
Translations stopped syncing

### ISSUE THREAD

**Issue by data-sync-user** [MozillaFoundation/foundation.mozilla.org#12101]
From Theo on #mofo-wagtail:

{quote}Hi, the sync_git command started crashing on Friday

it seem to crash when importing translations in [https://foundation.mozilla.org/cms/pages/2302/edit/](https://foundation.mozilla.org/cms/pages/2302/edit/)

I also can’t sync the translations on the What We Do page, but can’t see the logs so I don’t know if it’s related [https://foundation.mozilla.org/cms/localize/update/2/?next=%2Fcms%2Fpages%2F1128%2Fedit%2F](https://foundation.mozilla.org/cms/localize/update/2/?next=%2Fcms%2Fpages%2F1128%2Fedit%2F){quote}

```
INFO - Pull: Importing changes in file 'locales/nl/pages/homepage/what-we-do.po'
Traceback (most recent call last):
  File "/app/network-api/manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/wagtail_localize_git/management/commands/sync_git.py", line 19, in handle
    SyncManager(logger=logger).sync()
  File "/app/.heroku/python/lib/python3.11/site-packages/wagtail_localize_git/sync.py", line 190, in sync
    _pull(repo, self.logger)
  File "/app/.heroku/python/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/wagtail_localize_git/sync.py", line 49, in _pull
    importer.import_resource(translation, po)
  File "/app/.heroku/python/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/wagtail_localize_git/importer.py", line 22, in import_resource
    for warning in translation.import_po(po, tool_name="Pontoon"):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/wagtail_localize/models.py", line 1258, in import_po
    context = TranslationContext.objects.get(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(
wagtail_localize.models.TranslationContext.MultipleObjectsReturned: get() returned more than one TranslationContext -- it returned 2!
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/TP-394)

**Comment by data-sync-user** [comment]
➤ Jhonatan Lopes commented:

The issue was that this page had been updated before the data migration, so it already had strings with .external_url in it. Once the translations were synced, new TranslationContext objects were created when they should've been just updated. That's why we got the "MultipleObjectsReturned" exception. I manually deleted the offending TranslationContext objects from prod's db so that should do it

**Comment by data-sync-user** [comment]
➤ Jhonatan Lopes commented:

I used a db backup from last week (before the data migration that altered those objects) to find which TranslationContext objects had .external_url in their path:

from wagtail.models import Page
from wagtail_localize.models import TranslationSource, Translation, OverridableSegment, TranslationContext

contexts = TranslationContext.objects.filter(path__endswith=".external_url")
print("path,field_path,object_id,path_id")
for context in contexts:
    print(f'"{context.path}","{context.field_path or None}","{context.object_id}","{context.path_id}"')and then compared that to that query on the current DB. We can then search for TranslationContext objects that have the same object_id and path, as those are the determining parameters for the .get_or_create query.

After finding the duplicated TranslationContext objects, I used the following script to manually remove them from production’s database via heroku run "./network-api/manage.py" -a foundation-mozilla-org:

from wagtail_localize.models import TranslationContext

contexts_to_delete = [
    {
        "path": "body.355a0bf0-7ebe-4f3c-a2c6-c7e0de1e1d55.external_url",
        "field_path": "body.linkbutton.external_url",
        "object_id": "a081d230-0198-444c-8ed0-f9eb3deb5df7",
        "path_id": "03e49584-82e6-59ae-b7e2-e8c4c161cc30",
    },
    {
        "path": "body.f2ece2ca-bb5e-40bc-98d5-56539c649416.external_url",
        "field_path": "body.linkbutton.external_url",
        "object_id": "a081d230-0198-444c-8ed0-f9eb3deb5df7",
        "path_id": "ee7dfb09-9ae6-5575-bf70-a266b452196a",
    },
]

for context in contexts_to_delete:
    tc = TranslationContext.objects.get(
        path=context["path"],
        field_path=context["field_path"],
        object_id=context["object_id"],
        path_id=context["path_id"],
    )
    print(f'"{tc.path}","{tc.field_path or None}","{tc.object_id}","{tc.path_id}"')
    print(f"Deleting {tc}")
    tc.delete()

**Comment by data-sync-user** [comment]
➤ Jhonatan Lopes commented:

Theo has confirmed that the fix has solved the issue.
