### ISSUE TITLE
History of deleted pages crashes

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/foundation.mozilla.org#8423]
This query in the site history to list all recently deleted pages crashes: https://foundation.mozilla.org/cms/reports/site-history/?object_type=&label=&action=wagtail.delete&user=&timestamp_after=&timestamp_before=

This might be a wagtail 2.16 regression? I haven’t tried locally, but I assume this is triggered by specific data in our DB

```
2022-03-08T09:50:23.480966+00:00 app[web.1]: Internal Server Error: /cms/reports/site-history/

2022-03-08T09:50:23.480995+00:00 app[web.1]: Traceback (most recent call last):

2022-03-08T09:50:23.480996+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

2022-03-08T09:50:23.480996+00:00 app[web.1]:     response = get_response(request)

2022-03-08T09:50:23.480997+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

2022-03-08T09:50:23.480998+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)

2022-03-08T09:50:23.480998+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback

2022-03-08T09:50:23.480999+00:00 app[web.1]:     return callback(request, *args, **kwargs)

2022-03-08T09:50:23.480999+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner

2022-03-08T09:50:23.481000+00:00 app[web.1]:     return func(*args, **kwds)

2022-03-08T09:50:23.481000+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func

2022-03-08T09:50:23.481001+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)

2022-03-08T09:50:23.481001+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper

2022-03-08T09:50:23.481002+00:00 app[web.1]:     return view_func(request, *args, **kwargs)

2022-03-08T09:50:23.481002+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/auth.py", line 174, in decorated_view

2022-03-08T09:50:23.481002+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)

2022-03-08T09:50:23.481002+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view

2022-03-08T09:50:23.481003+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)

2022-03-08T09:50:23.481003+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch

2022-03-08T09:50:23.481003+00:00 app[web.1]:     return handler(request, *args, **kwargs)

2022-03-08T09:50:23.481003+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/views/reports/base.py", line 44, in get

2022-03-08T09:50:23.481004+00:00 app[web.1]:     context['object_list'] = self.decorate_paginated_queryset(context['object_list'])

2022-03-08T09:50:23.481005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/admin/views/reports/audit_logging.py", line 175, in decorate_paginated_queryset

2022-03-08T09:50:23.481005+00:00 app[web.1]:     for log_entry, instance in log_entries:

2022-03-08T09:50:23.481005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/wagtail/core/models/audit_log.py", line 66, in with_instances

2022-03-08T09:50:23.481005+00:00 app[web.1]:     model_instances = model.objects.in_bulk(object_ids)

2022-03-08T09:50:23.481006+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'objects'

**Comment by simont-cr** [comment]
Closing as obsolete issue as part of 2024 Clean-up.
